#!/bin/bash

# Old Author: Péricles Lopes Machado (eu[at]gogo40.com)

# Author: Ricardo Biehl Pasquali <rbpoficial@gmail.com>

script_name="ghostfs_mount"

function print_usage() {
	echo "Usage: $script_name [OPTIONS] <mount_point>"
	exit 1
}

function print_help {
	echo "$script_name -- Mount util for GhostFS"
	echo
	echo "  usage: $script_name [OPTIONS] <mount_point>"
	echo
	echo "    --help|-h  Show this help."
	echo "    --debug|-d  Active debug mode."
	echo
	echo "License: GNU/GPL (See COPYING); Author: Raphael S. Carvalho"
	exit 0
}

unset opt_arg

while [ 0 ]; do
	case "$1" in
	"--help"|"-h")
		print_help
	;;
	"--debug"|"-d")
		opt_arg="$opt_arg -d"
	;;
	*)
		break
	;;
	esac

	shift
done

if [ -z "$1" ]; then
	echo "No mount_point!"
	print_usage
fi

if [ ! -d "$1" ]; then
	echo "\"$1\" is not a directory!"
	print_usage
fi

mount_point="$1"

ghostfs $mount_point $opt_arg
